### ISSUE TITLE
Variable definition clarifications

### ISSUE THREAD

**Issue by Chronum94** [tgolubev/Drift-Diffusion_models-Cpp_Matlab#1]
I was hoping to get an update on a few variables which I didn't quite understand. I'm trying to understand the DD model, and the implementation of it, and this has been one of the most helpful codes so far, so I'm hoping to clarify what little I need from here itself.

In file `SG_2carriers.m`:

Lines 54 and 55: What exactly are `p` and `n`?
Line 66: Why increase tolerance for first 1st convergence?
Lines 95-96: I understand `V` is potential, I think; but what is `bV`?
Lines 100-102: What are `Cp`, `Cn`, and `CV`?
Lines 134-135: What are `bn` and `bp`? I can see they're related to electrons and holes, but I don't know how.

For now, this is as far into the code as I've gone. Any help with this would be greatly appreciated.

**Comment by tgolubev** [comment]
Thank you @Chronum94 for your interest in my code. To answer your questions:
1. `n` and `p` are the density of electrons and holes respectively
2. I find that the V=0 case (1st convergence) cannot converge to the lower tolerance. I am not sure exactly what is the reason for this. Maybe it is because we are converging from an initial guess for `n`, `p`, and `V` which could be far from the actual solution.
3. `bV`, `bn` and `bp` are the column vectors at the right hand sides of the matrix equations which we are solving. We have:

Poisson's equation: `Av *V = bV`
`bV` contains the boundary conditions for voltage in its 1st and last element and the rest is determined by `CV*(n-p)` which is just the total electric charge times some constants.

continuity/drift-diffusion:
`An * n = bn`
`Ap * p = bp`
`bn` and `bp` will contain the boundary conditions (charge densities at the boundaries) in their 1st and last elements and the rest of elements are `-Cn*Un` and `-Cp*Up` where `Un` and `Up` are the net electron and hole generation rates in the device.

`CV`, `Cn`, and `Cp` are just names for all of the constant coefficients which were grouped together in each equation. They are defined at the beginning of the 'solver loop'
`Cp = dx^2/(Vt*N*p_mob)`
`Cn = dx^2/(Vt*N*n_mob) ` 
`CV = N*dx^2*q/(epsilon*Vt)`
`Vt = (kb*T)/q` is the thermal voltage

I hope this helps.

**Comment by Chronum94** [comment]
It does. Thank you so much, both for making this code available and for the explanations.
